version: "3"
services:
  mysql:
    restart: always
    image: mysql
    container_name: mysql-server
    volumes:
      - /Users/jgchen/Desktop/docker/mysql/conf/my.cnf:/etc/my.cnf
      - /Users/jgchen/Desktop/docker/mysql/data:/var/lib/mysql
      - /Users/jgchen/Desktop/docker/mysql/log:/var/log/mysql
      # 数据库还原目录 可将需要还原的sql文件放在这里
      - /Users/jgchen/Desktop/docker/mysql/source:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "TZ=Asia/Shanghai"
    ports:
      # 使用宿主机的3306端口映射到容器的3306端口
      # 宿主机：容器
      - 3306:3306
